In [3]:
import cv2 as cv

In [2]:
# read image
image = cv.imread("../DATA/image1.png")

In [3]:
gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
print(gray)

[[163 163 163 ... 172 154 127]
 [163 156 163 ... 168 154 129]
 [163 163 163 ... 168 156 122]
 ...
 [ 40  43  48 ... 107 103  98]
 [ 43  43  50 ... 107 107 107]
 [ 40  43  54 ... 100 104 110]]


In [4]:
print(image.shape)

(512, 512, 3)


In [5]:
print(gray.shape)

(512, 512)


In [6]:
rgb_image = cv.imread("../DATA/rgb_image.jpg")

In [7]:
rgb_image = cv.cvtColor(rgb_image, cv.COLOR_BGR2RGB)

In [8]:
rgb_image.shape

(360, 639, 3)

In [9]:
rgb_image_1 = cv.imread("../DATA/colors.jpg")

In [10]:
rgb_image_1 = cv.cvtColor(rgb_image_1, cv.COLOR_BGR2RGB)

In [11]:
(R, G, B) = cv.split(image)

In [12]:
cv.namedWindow("Blue", cv.WINDOW_NORMAL)
cv.namedWindow("Green", cv.WINDOW_NORMAL)
cv.namedWindow("Red", cv.WINDOW_NORMAL)

In [13]:
cv.imshow("Blue", B)
cv.imshow("Green", G)
cv.imshow("Red", R)

In [14]:
cv.imwrite("channel_red.jpg", R)
cv.imwrite("channel_green.jpg", G)
cv.imwrite("channel_blue.jpg", B)
if cv.waitKey(0):
  cv.destroyAllWindows()

In [15]:
rgb_image_1 = cv.imread("../DATA/colors.jpg")
(b, g, r) = rgb_image_1[0, 0]
print(f"At pixel (0,0), - Red: {r}, Green: {g}, Blue: {b}")

At pixel (0,0), - Red: 42, Green: 141, Blue: 12


### Drawing

In [1]:
import numpy as np

In [4]:
canvas = np.zeros((300, 300, 3), dtype="uint8")

In [5]:
green = (0, 255, 0)
cv.line(canvas, (0, 0), (300, 300), green)
cv.imshow("Canvas", canvas)
cv.waitKey(0)

32

In [6]:
red = (0, 0, 255)
cv.line(canvas, (300, 0), (0, 300), red)
cv.imshow("Canvas", canvas)
cv.waitKey(0)

13

In [7]:
cv.rectangle(canvas, (50, 200), (200, 255), red, 5)
cv.imshow("Canvas", canvas)
cv.waitKey(0)

13

In [8]:
canvas = np.zeros((300, 300, 3), dtype="uint8")
canvas.shape

(300, 300, 3)

In [9]:
(centerX, centerY) = (canvas.shape[1] // 2, canvas.shape[0] // 2)
white = (255, 255, 255)

In [10]:
print(centerX, centerY)

150 150


In [11]:
for r in range(0, 175, 25):
  cv.circle(canvas, (centerX, centerY), r, white)

cv.imshow("Canvas", canvas)
cv.waitKey(0)

32

In [2]:
for i in range(0, 25):
  radius = np.random.randint(low=5, high=200)
  color = np.random.randint(low=0, high=200, size=(3,)).tolist()
  pt = np.random.randint(low=0, high=300, size=(2,))
  print(radius, color, pt)

180 [48, 78, 17] [166 213]
180 [90, 142, 79] [242 205]
109 [116, 39, 71] [ 29 288]
160 [80, 173, 25] [219 192]
134 [58, 65, 149] [216  58]
119 [150, 130, 17] [131 184]
51 [182, 50, 59] [287 191]
45 [11, 14, 113] [228 134]
177 [146, 166, 155] [227 123]
138 [58, 182, 44] [227 124]
169 [52, 47, 121] [130 127]
169 [144, 94, 100] [169  45]
129 [122, 185, 161] [251 149]
181 [106, 46, 140] [ 9 69]
115 [128, 52, 188] [280 117]
99 [84, 105, 64] [ 7 60]
31 [42, 96, 69] [121   9]
93 [35, 151, 184] [222  15]
111 [129, 71, 180] [136  92]
121 [69, 66, 162] [297 184]
74 [125, 198, 90] [263 173]
86 [89, 113, 113] [179 161]
152 [128, 64, 43] [132 299]
184 [23, 19, 161] [ 64 154]
157 [57, 7, 18] [262  50]


In [13]:
for i in range(0, 25):
  radius = np.random.randint(low=5, high=200)
  color = np.random.randint(low=0, high=200, size=(3,)).tolist()
  pt = np.random.randint(low=0, high=300, size=(2,))
  cv.circle(canvas, pt, radius, color, -1)
  
cv.imshow("Canvas", canvas)
cv.waitKey(0)

32

: 